apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-github-secret
spec:
  rules:
  - name: replicate-secret
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: v1
      kind: Secret
      name: flux-system
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: kube-system
        name: flux-system