apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-github-secret
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: replicate-secret
      match:
        any:
          - resources:
              kinds:
                - Secret
              names:
                - flux-system
              namespaces:
                - kube-system
      generate:
        kind: Secret
        name: flux-system
        namespace: "{{ request.object.metadata.namespace }}"
        synchronize: true
        data:
          apiVersion: v1
          kind: Secret
          metadata:
            name: flux-system
          data: "{{ request.object.data }}"
          type: Opaque