---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: vpa
spec:
  image: "qa.int.stratio.com:11443/autoscaling/vpa-admission-controller"
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: vpa
spec:
  imageRepositoryRef:
    name: vpa
  policy:
    semver:
      range: ">=0.13.0"
